{"name": "Test generate token with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x000001BE3F57FE00>"}], "start": 1702368257554, "stop": 1702368259232, "uuid": "5bea64a0-f360-4c49-9f59-3261a8663430", "historyId": "c6e94ff1741592559e5d3e6ead9538db", "testCaseId": "573dcf4d17f28e829fe2a39fec07d16d", "fullName": "testcases.api.test_generate_token#test_generate_token_unsuccessfully_with_invalid_account", "labels": [{"name": "parentSuite", "value": "API Test"}, {"name": "suite", "value": "Test Generate Token"}, {"name": "subSuite", "value": "TestGenerateToken"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "12448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api.test_generate_token"}]}