{"name": "Test login with a valid account", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16", "trace": "self = <testcases.ui.test_login.TestLogin object at 0x00000205A6188C80>, account = <data_object.account.Account object at 0x00000205A61369F0>\n\n    @allure.title(\"Test login with a valid account\")\n    @pytest.mark.smoke\n    @pytest.mark.parametrize(\"account\", Account.get_list_account_from_json('resources/test_data/account.json','valid'))\n    def test_login_successfully_with_valid_account(self, account):\n        book_store_page =  BookStorePage()\n        #book_store_page.go_to_login_page()\n    \n        login_page = LoginPage()\n>       login_page.login(account)\n\ntestcases\\ui\\test_login.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_object\\login_page.py:14: in login\n    self._username_textbox.enter(account.username)\ncore\\element\\element.py:81: in enter\n    self.scroll_into_view()\ncore\\element\\element.py:68: in scroll_into_view\n    self.wait_for_visibility()\ncore\\element\\element.py:17: in wait_for_visibility\n    self._element = WebDriverWait(self._driver, timeout).until(EC.visibility_of_element_located((self._by[0] , self._by[1])))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"52f47c7a-dbef-4527-894c-709b588adcec\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x00000205A61B5EE0>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "attachments": [{"source": "81ce087c-b0b6-4ad3-91a9-466d97f05f55-attachment.png", "type": "image/png"}], "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x00000205A61369F0>"}], "start": 1702398118756, "stop": 1702398123817, "uuid": "ed2b42d1-c5f7-4d3e-811c-380f8de357d3", "historyId": "f5e4fd3fd197906684d96e8894e8864b", "testCaseId": "692c73daca4b60a08ce08d1eeb31fd96", "fullName": "testcases.ui.test_login#test_login_successfully_with_valid_account", "labels": [{"name": "parentSuite", "value": "UI Test"}, {"name": "suite", "value": "Test Login"}, {"name": "tag", "value": "smoke"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "18072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.ui.test_login"}]}