{"name": "Test generate token with invalid accounts", "status": "passed", "parameters": [{"name": "account", "value": "<data_object.account.Account object at 0x00000205A6107740>"}], "start": 1702397948585, "stop": 1702397949701, "uuid": "ae13a4be-9901-4961-a720-e586c3399b29", "historyId": "0c41070497d273a8ad5ff38d6c423eaa", "testCaseId": "573dcf4d17f28e829fe2a39fec07d16d", "fullName": "testcases.api.test_generate_token#test_generate_token_unsuccessfully_with_invalid_account", "labels": [{"name": "parentSuite", "value": "API Test"}, {"name": "suite", "value": "Test Generate Token"}, {"name": "subSuite", "value": "TestGenerateToken"}, {"name": "host", "value": "VNNOT02222"}, {"name": "thread", "value": "18072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api.test_generate_token"}]}